### ISSUE TITLE
Authorization is broken

### ISSUE THREAD

**Issue by AlexSh77** [Sorrow446/SberZvuk-Downloader#16]
panic: Failed to get user info.
        403 Forbidden

goroutine 1 [running]:
main.handleErr({0x7ff6a8be54a7, 0x18}, {0x7ff6a8c86900?, 0xc000030f30?}, 0x1)
        r:/_FLAC/_ZVUK/main.go:88 +0xbf
main.main()
        r:/_FLAC/_ZVUK/main.go:994 +0x525
exit status 2

**Comment by AlexSh77** [comment]
Solved the problem!

Updated:
go mod init learn
go mod tidy

and replaced:
38 -	userAgent      = "OpenPlay|4.10.2|Android|7.1.2|Asus ASUS_Z01QD"
with
38 +	userAgent      = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 YaBrowser/24.10.0.0 Safari/537.36"
